name: CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy to Elastic Beanstalk
      run: |
        zip -r deploy.zip . -x .git/\*
        aws elasticbeanstalk create-application-version --application-name "git-hub-actions" --version-label ${{ github.sha }} --source-bundle S3Bucket=githubactions-bucket-haroon,S3Key=deploy.zip
        aws elasticbeanstalk update-environment --environment-name "Git-hub-actions-env" --version-label ${{ github.sha }}
